---
# Enviroment
env: dev

# Php
php_version:             7.1
#php_version_old:         7.0
php_fpm_socket:          /var/run/php-fpm.sock
php_memory_limit:        128M
php_date_timezone:       Australia/Melbourne
php_max_execution_time:  30
php_upload_max_filesize: 5M
php_session_save_path:   /var/lib/php/sessions

# Nginx
nginx_upload_max_filesize: 10M

# Symfony
site_domain: apna.local
site_url:    apna.local

# Database
database_name: apna
database_user: apna
database_pass: hs98WeTiUkz7
database_host: localhost

# Mail
mailer_transport:  smtp
mailer_host:       localhost
mailer_user:       ~
mailer_password:   ~
mailer_encryption: ~
mailer_port:       false

# Repository
repo_url:     git@github.com:rxpcollective/apna.git
repo_remote:  origin
repo_version: master

# Ansible
ansible_ssh_user: vagrant
# ansible_ssh_private_key_file: ''